services:
  iroh-relay:
    container_name: iroh-relay
    image: n0computer/iroh-relay:v0.34.1
    ports:
      - "127.0.0.1:31232:3478/udp"
      - "127.0.0.1:8084:80/tcp"
      - "127.0.0.1:9090:9090/tcp"
    restart: always
    command: ["--config-path", "/config/iroh-relay.toml"]
    environment:
      - RUST_LOG=debug
    deploy:
      resources:
        limits:
          memory: 600M
    volumes:
      - ./iroh-relay.toml:/config/iroh-relay.toml

  iroh-dns:
    container_name: iroh-dns
    image: n0computer/iroh-dns-server:v0.34.1
    ports:
      - "53:53/udp"
      - "127.0.0.1:18080:18080/tcp"
    restart: always
    volumes:
      - ./iroh-dns-server-dev.toml:/config/iroh-dns-server-dev.toml
    command: ["--config", "/config/iroh-dns-server-dev.toml"]
    environment:
      - RUST_LOG=debug
    deploy:
      resources:
        limits:
          memory: 420M

  clickhouse:
    container_name: clickhouse
    image: clickhouse:25.5
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_DB=sparganothis
      - CLICKHOUSE_USER=sparganothis
      - CLICKHOUSE_PASSWORD=sparganothis
    ports:
      - '127.0.0.1:8123:8123'
      - '127.0.0.1:9000:9000'
    volumes:
      - clickhouse_data3:/var/lib/clickhouse
      # - ./data:/var/lib/clickhouse/user_files
      - ./clickhouse_log_disable.xml:/etc/clickhouse-server/config.d/z_log_disable.xml
    healthcheck:
      test: wget --no-verbose --tries=1 http://127.0.0.1:8123/ping || exit 1
      interval: 13s
      timeout: 15s
      retries: 6
    memswap_limit: 2000M
    mem_limit: 2000M
    restart: unless-stopped
    
  clickhouse-monitoring:
    image: ghcr.io/duyet/clickhouse-monitoring:2cc8058
    environment:
      - "CLICKHOUSE_HOST=http://clickhouse:8123"
      - CLICKHOUSE_USER=sparganothis
      - CLICKHOUSE_PASSWORD=sparganothis
    depends_on:
      clickhouse:
        condition: service_healthy
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - /var/lib/clickhouse-monitoring
    memswap_limit: 1000M
    mem_limit: 1000M
    restart: unless-stopped


  ch-ui:
    image: ghcr.io/caioricciuti/ch-ui:sha-6227281d8c096e4259a1b96c92aa3f8d784a3c2b
    ports:
      - '127.0.0.1:5521:5521'
    depends_on:
      clickhouse:
        condition: service_healthy
    memswap_limit: 1000M
    mem_limit: 1000M
    restart: unless-stopped
    environment:
      VITE_CLICKHOUSE_URL: "http://localhost:8123"
      VITE_CLICKHOUSE_USER: "sparganothis"
      VITE_CLICKHOUSE_PASS: "sparganothis"



volumes:
  clickhouse_data3:
    driver: local
  bytebase:
    driver: local