pkarr_put_rate_limit = "disabled"

[http]
port = 18080
bind_addr = "0.0.0.0"

# [https]
# port = 18443
# bind_addr = "0.0.0.0"
# domains = ["v2.sparganothis.org"]
# cert_mode = "self_signed"

[dns]
port = 53
bind_addr = "0.0.0.0"
default_soa = "dns1.v2.sparganothis.org hostmaster.v2.sparganothis.org 0 10800 3600 604800 3600"
default_ttl = 900
origins = ["v2.sparganothis.org.", "."]
rr_a = "127.0.0.1"
rr_ns = "ns1.v2.sparganothis.org."

[mainline]
enabled = false
